name: Scheduled Data Scraping

on:
  schedule:
    # Run every 6 hours (adjust as needed)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Scraping API
        run: |
          curl -X POST "${{ secrets.SCRAPING_ENDPOINT }}" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"source": "github-actions", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}'

      - name: Check Response
        run: echo "Scraping job completed at $(date)"
