name: Trends Analysis Cron Job

on:
  schedule:
    # Run every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  analyze-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Trends Analysis
        run: |
          echo "🚀 Starting trends analysis..."

          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/cron/analyze-trends")

          http_code="${response: -3}"
          body="${response%???}"

          echo "HTTP Status: $http_code"
          echo "Response: $body"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ Trends analysis completed successfully"
          else
            echo "❌ Trends analysis failed with status $http_code"
            exit 1
          fi

      - name: Log Results
        if: always()
        run: |
          echo "📊 Trends Analysis Job Summary:"
          echo "- Timestamp: $(date)"
          echo "- Status: ${{ job.status }}"
          echo "- Repository: ${{ github.repository }}"
          echo "- Workflow: ${{ github.workflow }}"
